const MDD_SPECIES_LINK = "/taxon/";
const MDD_SPECIES_PERMALINK = "https://mammaldiversity.org";

// The actual permanent link is generated by Astro
// based on the folder structure and the [id] slug in the file name.
// This function is only useful for generating the link
// for the section in the species page.
/**
 * Generates a full permalink URL for a species page.
 * @param {number} taxonId - The ID of the taxon.
 * @returns {string} The full permalink URL for the species page.
 */
function generateSpeciesPermalink(taxonId: number): string {
  return `${MDD_SPECIES_PERMALINK}${MDD_SPECIES_LINK}${taxonId}`;
}

/**
 * Generates a relative link for a species page.
 * @param {number} taxonId - The ID of the taxon.
 * @returns {string} The relative link for the species page.
 */
function generateSpeciesLink(taxonId: number): string {
  return `${MDD_SPECIES_LINK}${taxonId}`;
}

function generateOrderLink(taxonName: string): string {
  return `/order/${taxonName}`;
}

function generateFamilyLink(taxonName: string): string {
  return `/family/${taxonName}`;
}

function generateCountryLink(countryCode: string): string {
  return `/country/${countryCode}`;
}

function generateCountryPermalink(countryCode: string): string {
  return `https://mammaldiversity.org/country/${countryCode}`;
}

function generateStateLink(countryCode: string, stateCode: string): string {
  return `/country/${countryCode}/${stateCode}`;
}

function generateStatePermalink(countryCode: string, stateCode: string): string {
  return `https://mammaldiversity.org/country/${countryCode}/${stateCode}`;
}

export {
  generateSpeciesLink,
  generateSpeciesPermalink,
  generateOrderLink,
  generateFamilyLink,
  generateCountryLink,
  generateCountryPermalink,
  generateStateLink,
  generateStatePermalink,
};
