const MDD_SPECIES_LINK = "/taxon/";
const MDD_SPECIES_PERMALINK = "https://mammaldiversity.org";

// The actual permanent link is generated by Astro
// based on the folder structure and the [id] slug in the file name.
// This function is only useful for generating the link
// for the section in the species page.
function generateSpeciesPermalink(taxonId: number): string {
  return `${MDD_SPECIES_PERMALINK}${MDD_SPECIES_LINK}${taxonId}`;
}

function generateSpeciesLink(taxonId: number): string {
  return `${MDD_SPECIES_LINK}${taxonId}`;
}

export { generateSpeciesLink, generateSpeciesPermalink };
