import { defineDb, defineTable, column } from "astro:db";

const Taxonomy = defineTable({
  columns: {
    id: column.number({ primaryKey: true }),
    phylosort: column.number({ optional: true }),
    subclass: column.text({ optional: true }),
    infraclass: column.text({ optional: true }),
    magnorder: column.text({ optional: true }),
    superorder: column.text({ optional: true }),
    taxonOrder: column.text({ optional: true }),
    suborder: column.text({ optional: true }),
    infraorder: column.text({ optional: true }),
    parvorder: column.text({ optional: true }),
    superfamily: column.text({ optional: true }),
    family: column.text({ optional: true }),
    subfamily: column.text({ optional: true }),
    tribe: column.text({ optional: true }),
    genus: column.text({ optional: true }),
    subgenus: column.text({ optional: true }),
    specificEpithet: column.text({ optional: true }),
    sciName: column.text({ optional: true }),
    authoritySpeciesAuthor: column.text({ optional: true }),
    authoritySpeciesYear: column.number({ optional: true }),
    authorityParentheses: column.number({ optional: true }),
    mainCommonName: column.text({ optional: true }),
    otherCommonNames: column.text({ optional: true }),
    originalNameCombination: column.text({ optional: true }),
    authoritySpeciesCitation: column.text({ optional: true }),
    authoritySpeciesLink: column.text({ optional: true }),
    typeVoucher: column.text({ optional: true }),
    typeKind: column.text({ optional: true }),
    typeVoucherURIs: column.text({ optional: true }),
    typeLocality: column.text({ optional: true }),
    typeLocalityLatitude: column.text({ optional: true }),
    typeLocalityLongitude: column.text({ optional: true }),
    nominalNames: column.text({ optional: true }),
    taxonomyNotes: column.text({ optional: true }),
    taxonomyNotesCitation: column.text({ optional: true }),
    distributionNotes: column.text({ optional: true }),
    distributionNotesCitation: column.text({ optional: true }),
    subregionDistribution: column.text({ optional: true }),
    countryDistribution: column.text({ optional: true }),
    continentDistribution: column.text({ optional: true }),
    biogeographicRealm: column.text({ optional: true }),
    iucnStatus: column.text({ optional: true }),
    extinct: column.number({ optional: true }),
    domestic: column.number({ optional: true }),
    flagged: column.number({ optional: true }),
    CMW_sciName: column.text({ optional: true }),
    diffSinceCMW: column.number({ optional: true }),
    MSW3_matchtype: column.text({ optional: true }),
    MSW3_sciName: column.text({ optional: true }),
    diffSinceMSW3: column.number({ optional: true }),
  },
});

const Synonym = defineTable({
  columns: {
    synId: column.number(),
    hespId: column.number({ optional: true }),
    speciesId: column.number({ optional: true }),
    species: column.text({ optional: true }),
    rootName: column.text({ optional: true }),
    author: column.text({ optional: true }),
    year: column.number({ optional: true }),
    authorityParentheses: column.number({ optional: true }),
    nomenclatureStatus: column.text({ optional: true }),
    validity: column.text({ optional: true }),
    originalCombination: column.text({ optional: true }),
    originalRank: column.text({ optional: true }),
    authorityCitation: column.text({ optional: true }),
    uncheckedAuthorityCitation: column.text({ optional: true }),
    sourcedUnverifiedCitations: column.text({ optional: true }),
    citationGroup: column.text({ optional: true }),
    citationKind: column.text({ optional: true }),
    authorityPage: column.text({ optional: true }),
    authorityLink: column.text({ optional: true }),
    authorityPageLink: column.text({ optional: true }),
    uncheckedAuthorityPageLink: column.text({ optional: true }),
    oldTypeLocality: column.text({ optional: true }),
    originalTypeLocality: column.text({ optional: true }),
    uncheckedTypeLocality: column.text({ optional: true }),
    emendedTypeLocality: column.text({ optional: true }),
    typeLatitude: column.text({ optional: true }),
    typeLongitude: column.text({ optional: true }),
    typeCountry: column.text({ optional: true }),
    typeSubregion: column.text({ optional: true }),
    typeSubregion2: column.text({ optional: true }),
    holotype: column.text({ optional: true }),
    typeKind: column.text({ optional: true }),
    typeSpecimenLink: column.text({ optional: true }),
    taxonOrder: column.text({ optional: true }),
    family: column.text({ optional: true }),
    genus: column.text({ optional: true }),
    specificEpithet: column.text({ optional: true }),
    subspecificEpithet: column.text({ optional: true }),
    variantOf: column.text({ optional: true }),
    seniorHomonym: column.text({ optional: true }),
    variantNameCitations: column.text({ optional: true }),
    nameUsages: column.text({ optional: true }),
    comments: column.text({ optional: true }),
  },
});

// https://astro.build/db/config
export default defineDb({
  tables: { Taxonomy, Synonym },
});
